site_name: OT Piece Wiki
site_description: Wiki oficial do servidor OT Piece

theme:
  name: material
  language: pt
  
  palette:
    scheme: slate        # Força tema escuro
    primary: deep purple
    accent: orange

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest

nav:
  - 🏠 Home: index.md
  - 👥 Personagens: personagens.md
  - ⚔️ Itens: itens.md
  - 📜 Quests: quests.md
  - 🗺️ Mapas: mapas.md
  - ℹ️ Sobre: sobre.md
