site_name: OT Piece Wiki
site_description: Wiki oficial do servidor OT Piece

theme:
  name: material
  language: pt
  
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - content.code.copy

  palette:
    primary: deep purple
    accent: orange
    scheme: slate   # Força o tema escuro

nav:
  - 🏠 Home: index.md
  - 👥 Personagens: personagens.md
  - ⚔️ Itens: itens.md
  - 📜 Quests: quests.md
  - 🗺️ Mapas: mapas.md
  - ℹ️ Sobre: sobre.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
