site_name: OT Piece Wiki
site_description: Wiki oficial do servidor OT Piece

theme:
  name: material
  language: pt

nav:
  - 🏠 Home: index.md
  - 👥 Personagens: personagens.md
  - ⚔️ Itens: itens.md
  - 📜 Quests: quests.md
  - 🗺️ Mapas: mapas.md
  - ℹ️ Sobre: sobre.md
